project_hoinhabao_homepage:
    path:     /hoivien/
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:index }

project_hoinhabao_add:
    path:     /hoivien/add
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:add }

project_hoinhabao_report:
    path:     /hoivien/report
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:report }

project_giaithuong_multidelete:
    path:     /hoivien/{tendangnhap}/giaithuong/delete
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:multidelete }

project_tacpham_multidelete:
    path:     /hoivien/{tendangnhap}/tacpham/delete
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:multidelete }

project_hoivien_multidelete:
    path:     /hoivien/delete
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:multidelete }

project_hoinhabao_show:
    path:     /hoivien/{tendangnhap}
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:show }

project_hoinhabao_edit:
    path:     /hoivien/{tendangnhap}/edit
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:edit }

project_hoinhabao_delete:
    path:     /hoivien/{tendangnhap}/delete
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:delete }


project_tacpham:
    path:     /hoivien/{tendangnhap}/tacpham
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:index }

project_tacpham_add:
    path:     /hoivien/{tendangnhap}/addtacpham
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:add }

project_giaithuong_add:
    path:     /hoivien/{tendangnhap}/addgiaithuong
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:add }

project_giaithuong:
    path:     /hoivien/{tendangnhap}/giaithuong
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:index }


project_tacpham_show:
    path:     /hoivien/{tendangnhap}/{matacpham}
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:show }

project_tacpham_edit:
    path:     /hoivien/{tendangnhap}/edit/{matacpham}
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:edit }

project_tacpham_delete:
    path:     /hoivien/{tendangnhap}/delete/{matacpham}
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:delete }




project_giaithuong_edit:
    path:     /hoivien/{tendangnhap}/{magiaithuong}/edit
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:edit }

project_giaithuong_delete:
    path:     /hoivien/{tendangnhap}/{magiaithuong}/delete
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:delete }

project_template:
    path: /hoivien
    defaults: { _controller: ProjectHoinhabaoBundle:Template:change }

