project_hoinhabao_homepage:
    path:     /hoivien/
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:index }

project_hoinhabao_add:
    path:     /hoivien/add
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:add }


project_hoinhabao_show:
    path:     /hoivien/{tendangnhap}
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:show }

project_hoinhabao_edit:
    path:     /hoivien/{tendangnhap}/edit
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:edit }

project_hoinhabao_delete:
    path:     /hoivien/{tendangnhap}/delete
    defaults: { _controller: ProjectHoinhabaoBundle:Hoivien:delete }


project_tacpham:
    path:     /hoivien/{tendangnhap}/tacpham
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:index }

project_tacpham_add:
    path:     /hoivien/{tendangnhap}/add
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:add }

project_tacpham_edit:
    path:     /hoivien/{tendangnhap}/{tentacpham}/edit
    defaults: { _controller: ProjectHoinhabaoBundle:Tacpham:edit }


project_giathuong_add:
    path:     /hoivien/{tendangnhap}/addgiaithuong
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:add }

project_giathuong_edit:
    path:     /hoivien/{tendangnhap}/{magiaithuong}/edit
    defaults: { _controller: ProjectHoinhabaoBundle:Giaithuong:edit }

