<?php

namespace Proxies\__CG__\Project\HoinhabaoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hoivien extends \Project\HoinhabaoBundle\Entity\Hoivien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'tendangnhap', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'matkhau', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'hoten', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'ngaysinh', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'gioitinh', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'anhdaidien', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'quequan', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'email', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'cmnd', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'tieusu', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'kichhoat', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'mahv', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'matoasoan');
        }

        return array('__isInitialized__', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'tendangnhap', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'matkhau', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'hoten', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'ngaysinh', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'gioitinh', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'anhdaidien', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'quequan', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'email', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'cmnd', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'tieusu', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'kichhoat', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'mahv', '' . "\0" . 'Project\\HoinhabaoBundle\\Entity\\Hoivien' . "\0" . 'matoasoan');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hoivien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTendangnhap($tendangnhap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTendangnhap', array($tendangnhap));

        return parent::setTendangnhap($tendangnhap);
    }

    /**
     * {@inheritDoc}
     */
    public function getTendangnhap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTendangnhap', array());

        return parent::getTendangnhap();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatkhau($matkhau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatkhau', array($matkhau));

        return parent::setMatkhau($matkhau);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatkhau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatkhau', array());

        return parent::getMatkhau();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoten($hoten)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoten', array($hoten));

        return parent::setHoten($hoten);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoten()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoten', array());

        return parent::getHoten();
    }

    /**
     * {@inheritDoc}
     */
    public function setNgaysinh($ngaysinh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgaysinh', array($ngaysinh));

        return parent::setNgaysinh($ngaysinh);
    }

    /**
     * {@inheritDoc}
     */
    public function getNgaysinh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgaysinh', array());

        return parent::getNgaysinh();
    }

    /**
     * {@inheritDoc}
     */
    public function setGioitinh($gioitinh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGioitinh', array($gioitinh));

        return parent::setGioitinh($gioitinh);
    }

    /**
     * {@inheritDoc}
     */
    public function getGioitinh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGioitinh', array());

        return parent::getGioitinh();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnhdaidien($anhdaidien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnhdaidien', array($anhdaidien));

        return parent::setAnhdaidien($anhdaidien);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnhdaidien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnhdaidien', array());

        return parent::getAnhdaidien();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuequan($quequan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuequan', array($quequan));

        return parent::setQuequan($quequan);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuequan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuequan', array());

        return parent::getQuequan();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmnd($cmnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmnd', array($cmnd));

        return parent::setCmnd($cmnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmnd', array());

        return parent::getCmnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTieusu($tieusu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTieusu', array($tieusu));

        return parent::setTieusu($tieusu);
    }

    /**
     * {@inheritDoc}
     */
    public function getTieusu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTieusu', array());

        return parent::getTieusu();
    }

    /**
     * {@inheritDoc}
     */
    public function setKichhoat($kichhoat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKichhoat', array($kichhoat));

        return parent::setKichhoat($kichhoat);
    }

    /**
     * {@inheritDoc}
     */
    public function getKichhoat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKichhoat', array());

        return parent::getKichhoat();
    }

    /**
     * {@inheritDoc}
     */
    public function getMahv()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMahv();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMahv', array());

        return parent::getMahv();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatoasoan(\Project\HoinhabaoBundle\Entity\Toasoan $matoasoan = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatoasoan', array($matoasoan));

        return parent::setMatoasoan($matoasoan);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatoasoan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatoasoan', array());

        return parent::getMatoasoan();
    }

}
